### ISSUE TITLE
Add Footers, Organize files and Minor Style Corrections

### ISSUE THREAD

**Issue by Dinkar850** [Nikhil-gi/Wander-nest#15]
-> Adding responsiveness for a neat look in the Landing Page. 
Before: 

![Screenshot (1106)](https://github.com/user-attachments/assets/4a7fcfc1-2044-4320-8c08-cd0b964b0110)

After: 

![Screenshot (1107)](https://github.com/user-attachments/assets/7f2c9215-3344-4831-8a61-b4cc315ea58b)

-> Correcting Style in the grid in Most Visited Places

From this: 

![Screenshot (1108)](https://github.com/user-attachments/assets/0e17bdc0-eadb-4560-ad93-664f9cb4cc77)

To this: 

![Screenshot (1109)](https://github.com/user-attachments/assets/88b46114-5191-41ed-9589-a60dfadc99ad)

-> Will also add a properly styled footer section. 

Please assign me this issue under Hacktoberfest 2024.

**Comment by Nikhil-gi** [comment]
Hi @Dinkar850 ,

I’m assigning you the task to add responsiveness to the website, implement a footer, and make some minor style corrections in the "Most Visited Places" section. Please ensure the design remains consistent across different devices, and that the footer matches the overall theme of the site.

Regards,
@Nikhil-gi

**Comment by Dinkar850** [comment]
@Nikhil-gi 
Thank you for assigning me this issue. I'll keep the mentioned points in mind.
