### ISSUE TITLE
Addition of CONTRIBUTING.md

### ISSUE THREAD

**Issue by shash369** [Nikhil-gi/Wander-nest#3]
This issue aims to create a CONTRIBUTING.md file for the project to provide clear guidelines for potential contributors. 

please assign me the task under hacktoberfest-2024 .

**Comment by Nikhil-gi** [comment]
Go ahead! 
Thank you for raising this issue. Creating a CONTRIBUTING.md file is a great idea to help streamline the contribution process and set clear expectations for contributors. It will certainly improve collaboration and maintain consistency in the project.

I would suggest including sections on coding standards, the PR process, issue reporting guidelines, and any other specific practices we follow. Let me know if you'd like assistance drafting the document.

Best regards,
Nikhil
