### ISSUE TITLE
 Adding and Correcting Styles in the Landing Page

### ISSUE THREAD

**Issue by Dinkar850** [Nikhil-gi/Wander-nest#9]
![Screenshot (1105)](https://github.com/user-attachments/assets/a09992b9-5b9e-4a00-b60f-a75518da2913)
-> Centering main content in the hero section.
-> Adding 3D effect and animations to button and styling them to look professional.
-> Fixing an image issue in Most Loved Places section and adding cards.
-> Adding good fonts to make the website look more professional.

Please assign me this issue

**Comment by Nikhil-gi** [comment]
Hi @Dinkar850 ,

I've assigned this issue to you. Please work on the following:

> Center the main content in the hero section.
> Add 3D effects and animations to buttons for a professional look.
> Fix the image issue in the Most Loved Places section and add cards.
> Update fonts to make the website more professional.

Regards
@Nikhil-gi

**Comment by Dinkar850** [comment]
Thankyou so much for assigning me this issue. I have raised a PR for the same. Kindly review. 

I have also raised an issue #15 for adding responsiveness as a part of another commit in the project, with some additional style correction in Most Visited Places. I will also add a footer section with proper styling.

**Comment by Dinkar850** [comment]
@Nikhil-gi 
I have raised another PR #18 for this issue with some other recommended changes. Please review!
